# Generated by Django 4.2.1 on 2023-05-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='buy_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='sale_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
