# Generated by Django 4.2.1 on 2023-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0002_alter_exchangerates_buy_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerates',
            name='date_rate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
